import PptxGenJS from 'pptxgenjs';

interface ExportParams {
  player: Record<string, unknown>;
  content: Record<string, string>;
  audienceLabel: string;
  language: string;
}

const EMERALD = '10b981';
const DARK    = '111827';
const GRAY    = '6b7280';
const WHITE   = 'FFFFFF';
const LIGHT   = 'f3f4f6';

export async function generatePPT({ player, content, audienceLabel, language }: ExportParams): Promise<Buffer> {
  const pptx = new PptxGenJS();
  pptx.layout = 'LAYOUT_WIDE';
  pptx.author = 'ScoutIQ';
  pptx.subject = `${audienceLabel} Report`;
  pptx.title = `ScoutIQ — ${String(player.name ?? '')}`;

  // --- Title slide ---
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: DARK };

  titleSlide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: 0.3, h: 5.63, fill: { color: EMERALD } });

  titleSlide.addText('ScoutIQ', {
    x: 0.6, y: 0.5, w: 8, h: 0.6,
    fontSize: 28, bold: true, color: EMERALD, fontFace: 'Arial',
  });

  titleSlide.addText(`${audienceLabel} Report`, {
    x: 0.6, y: 1.2, w: 8, h: 0.5,
    fontSize: 18, color: WHITE, fontFace: 'Arial',
  });

  titleSlide.addText(String(player.name ?? ''), {
    x: 0.6, y: 2.0, w: 8, h: 0.7,
    fontSize: 32, bold: true, color: WHITE, fontFace: 'Arial',
  });

  const subtitle = [player.position, player.current_club, player.league, player.age ? `Age ${player.age}` : null]
    .filter(Boolean).join(' · ');
  titleSlide.addText(subtitle, {
    x: 0.6, y: 2.8, w: 8, h: 0.4,
    fontSize: 14, color: GRAY, fontFace: 'Arial',
  });

  titleSlide.addText(`Language: ${language.toUpperCase()}  ·  Generated by ScoutIQ`, {
    x: 0.6, y: 5.0, w: 8, h: 0.3,
    fontSize: 9, color: GRAY, fontFace: 'Arial',
  });

  // --- Content slides (one per section) ---
  for (const [key, value] of Object.entries(content)) {
    if (!value) continue;

    const slide = pptx.addSlide();
    slide.background = { color: WHITE };

    // Top bar
    slide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: 10, h: 0.55, fill: { color: DARK } });
    slide.addText('ScoutIQ', { x: 0.2, y: 0.1, w: 2, h: 0.35, fontSize: 11, bold: true, color: EMERALD, fontFace: 'Arial' });
    slide.addText(String(player.name ?? ''), { x: 2.5, y: 0.1, w: 5, h: 0.35, fontSize: 10, color: WHITE, fontFace: 'Arial' });

    // Section title
    const title = key.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
    slide.addShape(pptx.ShapeType.rect, { x: 0.3, y: 0.8, w: 0.07, h: 0.45, fill: { color: EMERALD } });
    slide.addText(title, {
      x: 0.5, y: 0.8, w: 9, h: 0.45,
      fontSize: 18, bold: true, color: DARK, fontFace: 'Arial',
    });

    // Body text
    slide.addText(String(value), {
      x: 0.3, y: 1.5, w: 9.4, h: 3.8,
      fontSize: 12, color: '374151', fontFace: 'Arial',
      valign: 'top', wrap: true,
    });

    // Footer
    slide.addShape(pptx.ShapeType.rect, { x: 0, y: 5.3, w: 10, h: 0.33, fill: { color: LIGHT } });
    slide.addText('AI-generated content uses only provided data. ScoutIQ · scoutiq.app', {
      x: 0.3, y: 5.33, w: 9.4, h: 0.27,
      fontSize: 7, color: GRAY, fontFace: 'Arial',
    });
  }

  const buf = (await pptx.write({ outputType: 'nodebuffer' })) as Buffer;
  return buf;
}
