import { createClient } from '@/lib/supabase/server';
import { Lock, Radio } from 'lucide-react';
import Link from 'next/link';

export default async function MarketIntelligencePage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  const { data: profile } = await supabase
    .from('users')
    .select('plan')
    .eq('id', user!.id)
    .single();

  const isElite = profile?.plan === 'elite';

  if (!isElite) {
    return (
      <div className="max-w-xl mx-auto text-center py-20">
        <Lock size={40} className="mx-auto text-gray-600 mb-4" />
        <h1 className="text-xl font-bold text-white mb-2">Market Intelligence</h1>
        <p className="text-gray-400 mb-2">
          Daily transfer signals personalised to your club profile.
        </p>
        <ul className="text-sm text-gray-500 space-y-1 mb-6">
          <li>🔥 HOT / ⚡ WARM / ● EARLY heat classification</li>
          <li>Alternative candidates auto-generated by AI</li>
          <li>Register up to 3 clubs</li>
          <li>Email alerts when signals match your clubs</li>
        </ul>
        <Link
          href="/settings#plans"
          className="bg-emerald-500 hover:bg-emerald-400 text-white font-semibold px-6 py-3 rounded-lg transition-colors"
        >
          Upgrade to Elite →
        </Link>
        <p className="text-xs text-gray-700 mt-4">€29/mo · Cancel anytime</p>
      </div>
    );
  }

  const { data: signals } = await supabase
    .from('transfer_signals')
    .select('*')
    .order('detected_at', { ascending: false })
    .limit(50);

  return (
    <div className="max-w-4xl mx-auto">
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <Radio size={20} className="text-emerald-400" />
          <h1 className="text-2xl font-bold text-white">Market Intelligence</h1>
        </div>
        <Link
          href="/market-intelligence/clubs"
          className="text-sm text-emerald-400 hover:text-emerald-300 border border-emerald-500/30 px-3 py-1.5 rounded-lg transition-colors"
        >
          Manage clubs
        </Link>
      </div>

      {!signals?.length ? (
        <div className="text-center py-20 text-gray-600">
          <div className="text-5xl mb-4">📡</div>
          <p className="text-gray-400 text-lg font-medium mb-2">No signals yet</p>
          <p className="text-sm">Register your club to receive personalised transfer signals daily at 6am</p>
          <Link href="/market-intelligence/clubs" className="mt-4 inline-block text-emerald-400 hover:text-emerald-300">
            Register a club →
          </Link>
        </div>
      ) : (
        <div className="space-y-3">
          {signals.map((s: SignalRow) => (
            <div key={s.id} className="bg-gray-900 border border-gray-800 rounded-xl p-5">
              <div className="flex items-start justify-between gap-4">
                <div className="flex-1">
                  <div className="flex items-center gap-3 flex-wrap mb-2">
                    <HeatBadge heat={s.heat} />
                    <span className={`text-xs px-2 py-0.5 rounded-full border ${
                      s.confidence === 'confirmed' ? 'border-emerald-500/30 text-emerald-400' :
                      s.confidence === 'rumour' ? 'border-yellow-500/30 text-yellow-400' :
                      'border-gray-600 text-gray-500'
                    }`}>
                      {s.confidence}
                    </span>
                    <span className="text-xs text-gray-600">{s.position}</span>
                  </div>
                  <div className="font-semibold text-white">
                    <span className="text-emerald-400">{s.interested_club}</span>
                    {' tracking '}
                    <Link href={`/players?q=${encodeURIComponent(s.target_player)}`} className="hover:text-emerald-400 transition-colors">
                      {s.target_player}
                    </Link>
                    {' from '}
                    <span>{s.target_club}</span>
                  </div>
                  {s.quote && (
                    <p className="text-sm text-gray-500 mt-2 italic">&ldquo;{s.quote}&rdquo;</p>
                  )}
                  <div className="text-xs text-gray-700 mt-2">
                    {s.source} · {new Date(s.detected_at).toLocaleDateString()}
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      <div className="mt-6 text-xs text-gray-700 p-4 bg-gray-900 border border-gray-800 rounded-xl">
        ⓘ Transfer signals are based on media reports and rumours. ScoutIQ does not verify the accuracy of transfer interest information.
      </div>
    </div>
  );
}

function HeatBadge({ heat }: { heat: string }) {
  const config: Record<string, { label: string; className: string }> = {
    hot: { label: '🔥 HOT', className: 'bg-red-500/10 text-red-400 border border-red-500/20' },
    warm: { label: '⚡ WARM', className: 'bg-orange-500/10 text-orange-400 border border-orange-500/20' },
    early: { label: '● EARLY', className: 'bg-blue-500/10 text-blue-400 border border-blue-500/20' },
  };
  const c = config[heat] ?? config.early;
  return (
    <span className={`text-xs font-bold px-2.5 py-0.5 rounded-full ${c.className}`}>
      {c.label}
    </span>
  );
}

interface SignalRow {
  id: string;
  interested_club: string;
  target_player: string;
  target_club: string;
  position: string;
  heat: string;
  confidence: string;
  source: string;
  quote: string;
  detected_at: string;
}
